---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atomist-bot
  labels:
    app: atomist-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atomist-bot
  template:
    metadata:
      labels:
        app: atomist-bot
    spec:
      containers:
        - name: atomist-bot
          image: eldermael/bot:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 2866
          envFrom:
            - secretRef:
                name: sdm-auth
---
kind: Service
apiVersion: v1
metadata:
  name: atomist-bot-service
spec:
  selector:
    app: atomist-bot
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 2866
      targetPort: 2866
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: atomist-bot
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  backend:
    serviceName: atomist-bot-service
    servicePort: 2866
  tls:
    - hosts:
        - atomist.eldermael.io
      secretName: atomist-eldermael-io-crt
